from setuptools import find_packages, setup

setup(
    name='phlower',
    version='0.1.3',
    description='hodge decomposition trajectory',
    url='https://github.com/CostaLab/phlower',
    author='Mingbo Cheng',
    author_email='chengmingbo@gmail.com',
    license='BSD 2-clause',
    install_requires=['numpy',
                      'matplotlib',
                      'seaborn>=0.12.2',
                      'networkx>=2.4',
                      'pydot',
                      'igraph',
                      "scikit-learn",
                      "scipy",
                      "pandas>=1.5.3",
                      "plotly",
                      "tqdm",
                      "leidenalg",
                      "louvain",
                      "colorcet",
                      'umap-learn',
                      'scikit-sparse', #deb:libsuitesparse-dev, conda:suitesparse
                      'scanpy',
                      'adjustText',
                      #'pygraphviz',
                      'magic-impute',
                      'anndata',
                      ],
    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    packages=find_packages()
)

