from setuptools import setup

setup(
    name='hodgetraj',
    version='0.1.1',
    description='hodge decomposition trajectory',
    url='https://github.com/CostaLab/hodgeTrajectory',
    author='Mingbo Cheng',
    author_email='chengmingbo@gmail.com',
    license='BSD 2-clause',
    packages=['hodgetraj'],
    install_requires=['numpy',
                      'matplotlib',
                      'seaborn',
                      'networkx>=2.4',
                      'igraph',
                      "sklearn",
                      "scipy",
                      "pandas",
                      "tqdm",
                      "leidenalg",
                      "louvain",
                      "colorcet",
                      'umap-learn',
                      ],

    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
)

